apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 4.1.0
    listeners:
      # Listener for internal cluster communication (pods)
      - name: plain
        port: 9092
        type: internal
        tls: false
      # Listener for external communication (your local machine / UI)
      - name: external
        port: 9094
        type: nodeport
        tls: false
  
  # Your Entity Operator is still correct
  entityOperator:
    topicOperator: {}
    userOperator: {}